### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#103]
@vykster would like a favicon inspired by the new homepage icons (with colors):

![image](https://github.com/compilerla/compiler.la/assets/1783439/297137ed-3d11-4765-8c68-ef987c7f3b38)

As Vyki says:

> Colors with a transparent background

**Comment by segacy1** [comment]
Thoughts on any of these @thekaveman ? Happy to iterate 
<img width="408" alt="favicon-r1" src="https://github.com/compilerla/compiler.la/assets/33331853/868a184a-190a-4161-96e4-89514bf9ef6e">

**Comment by AnthonyRollins** [comment]
@segacy1 7 and 8 (especially with the additional purple suggestion above) look good.

**Comment by thekaveman** [comment]
@segacy1 or maybe, at the risk of offending your design sensibilities, adding a small purple circle to the empty space on 8?

**Comment by thekaveman** [comment]
Vyki commented that 3/7/11 are closest to our actual "brand mark" i.e. the one that came out of the design process from Sublation a few years ago. 

So I think we should probably stick to one of those but with the added pops of color over the straight black/white version.

**Comment by segacy1** [comment]
It has been many months!! I'm pulling in 3rd for us to use because:

1. It's one of the options Vyki mentioned
2. I think at such a small size, the white rectangle will look better with a fill as it is here vs. an outline as it is in 7

That said, they're all options are saved in [Figma](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=1821-3916&mode=design) if you'd like to try! 

@AnthonyRollins because there is a black fill included, it shouldn't matter if you're in light or dark mode!
<img width="56" alt="Favicon" src="https://github.com/compilerla/compiler.la/assets/33331853/b976e334-64fd-4b60-babf-3941e01788ec">

**Comment by angela-tran** [comment]
New favicon is live on the website! 

If your browser is using a cached old favicon on https://compiler.la, try <kbd>Ctrl</kbd> + <kbd>F5</kbd> to do a refresh without cached content
