### ISSUE TITLE
Do a final pass on copy

### ISSUE THREAD

**Issue by thekaveman** [compilerla/compiler.la#231]
Of the content on https://deploy-preview-208--compilerla.netlify.app/our-work

**Comment by machikoyasuda** [comment]
Summary of copy notes:

- Match up tenses: All of the Outcomes section use a past tense verb like `launched` or `increased`, except the Product Schedule one is present tense (`deliver`).
- Use consistent naming style: Caltrans, not CalTrans.
- Monterey-Salinas Transit
- "tapping to pay" not "tapping-to-pay" - this "tapping-to-pay" is on the About page too
-  Make sure capitalization style is consistent across pages: "Customer Success Strategy" is titled cased on Work page but it's "Customer Success strategy" on the About page. Decide on whether Capabilities Statement is title-cased or sentence-cased and stick to it everywhere.
- Older adults, not seniors. Match up capitalization: If you want to capitalize Older adults, Veterans, then also capitalize Low-income and Disabled people. Or don't capitalize anything.
- Spell out names on first reference, then show the abbreviation in parenthesis. Then use the abbreviation thereafter.
- I personnally don't think "California Transit Agencies" should be capitalized because it might make people thing CTA is a single agency or something. 
- This is a run-on sentence: "In collaboration with government partners, Compiler produced and managed monthly community events, Data + Donuts since 2017—past speakers; LA Metro, California Department of Technology (CDT), SCAG and Caltrans." Maybe make the later half its own sentence. Example "Past speakers have included technology and policy leaders from LA Metro, California Department of Technology (CDT), SCAG and Caltrans."

**Comment by indexing** [comment]
For the Benefits section, I propose the following copy to replace the existing.

### Cal-ITP Benefits
Designed and developed a web application that allows transit riders to digitally verify their identity, check their eligibility for reduced transit fares, and enroll their credit or debit card to automatically receive a reduced fare on transit when they tap-to-pay.

### OUTCOME
Monterey-Salinas Transit (MST) was the first transit operator in California to adopt the Benefits app in 2022. Santa Barbara Metropolitan Transit District (SBMTD) launched in 2023, and several more operators are expected to launch in 2024. The app supports benefits enrollment for older adults, veterans, and CalFresh cardholders. Future enrollment options include Medicare cardholders and persons with disabilities.

**Comment by AnthonyRollins** [comment]
@compilerla/engineering responses below:

> Andy's updates to Benefits content:

As long as we are good on the character count, these changes looks good to me.

> Match up tenses: All of the Outcomes section use a past tense verb like launched or increased, except the Product Schedule one is present tense (deliver).

Let's change `Product Schedule` to match the tense of the other case studies. Change outcome wording from `Deliver` to `Delivered`.

> Use consistent naming style: Caltrans, not CalTrans.

Let's use Caltrans

> Monterey-Salinas Transit

Include hyphenate
 
> "tapping to pay" not "tapping-to-pay" - this "tapping-to-pay" is on the About page too

Use `tapping to pay`

> Make sure capitalization style is consistent across pages: "Customer Success Strategy" is titled cased on Work page but it's "Customer Success strategy" on the About page. Decide on whether Capabilities Statement is title-cased or sentence-cased and stick to it everywhere.

Let's use sentence case for `Customer Success strategy` and other case studies. For Capabilities Statement, I feel like we should use title case for that.

> Older adults, not seniors. Match up capitalization: If you want to capitalize Older adults, Veterans, then also capitalize Low-income and Disabled people. Or don't capitalize anything.

Andy used lower case for all enrollment pathways, so let's go with that. 

> Spell out names on first reference, then show the abbreviation in parenthesis. Then use the abbreviation thereafter.

Agreed.

> I personnally don't think "California Transit Agencies" should be capitalized because it might make people thing CTA is a single agency or something.

Agreed.

> This is a run-on sentence: "In collaboration with government partners, Compiler produced and managed monthly community events, Data + Donuts since 2017—past speakers; LA Metro, California Department of Technology (CDT), SCAG and Caltrans." Maybe make the later half its own sentence. Example "Past speakers have included technology and policy leaders from LA Metro, California Department of Technology (CDT), SCAG and Caltrans."

We can spilt into two sentences as long as we are good on character count.

**Comment by thekaveman** [comment]
@machikoyasuda @AnthonyRollins @indexing all copy suggestions/updates have been applied. Except for:

> Let's use sentence case for `Customer Success strategy`0 and other case studies.

This was the only case study where sentence casing would change the title, the others are more like the title of the application/program itself (D+D, Benefits, ODS). So I left it as-is for this one (Title Case).

I propose in the future we de-dupe the content on `/about` and `/our-work`, potentially by pulling in the same case study data in `/about` and showing e.g. only the title + summary or something like that.

**Comment by thekaveman** [comment]
@AnthonyRollins approved: https://compilerla.slack.com/archives/C04BN95SH0S/p1720816304941469?thread_ts=1720567710.239739&cid=C04BN95SH0S
