### ISSUE TITLE
Update employees listed under "Meet the team" on About page

### ISSUE THREAD

**Issue by angela-tran** [compilerla/compiler.la#242]
- [ ] Add [Andy](https://drive.google.com/file/d/1lMC0cAMgQcu_3Bb82SAddcGxUbB236Bm/view?usp=drive_link) Product Manager
- [ ] Add [Leela](https://drive.google.com/file/d/1ni0H-9SRD8TlEOFzX4KuIm9q4KgEm18Y/view?usp=drive_link) Senior Project Manager
- [ ] Remove Marissa
- [ ] Remove Sarah

**Comment by thekaveman** [comment]
Ugh, why do the images themselves have rounded corners vs. we just do that in CSS?

Does anyone know the corner radius for these images? @AnthonyRollins @angela-tran @machikoyasuda

**Comment by thekaveman** [comment]
> I'm not sure who has been preparing them when we add new team members

Yeah I figured it was a mix of folks.

> Would it be easier to make all the images not have rounded corners and then apply a border-radius through CSS?

I think it would mean one less step in the preparation process if we applied the border-radius through CSS. My process was:

1. Click link from Anthony above to raw `.png`, download locally, open in GIMP
2. Add layer for background color (white) since default background is transparent
3. Crop image to roughly the dimensions we want
4. Scale image to `300x267` pixels
5. _have to apply border radius in GIMP_

However, that means _unapplying_ the border-radius from all the existing images, which could take some time...

**Comment by lalver1** [comment]
I like the approach of using CSS instead for the rounded corners 👍 (when I worked on [PR #193](https://github.com/compilerla/compiler.la/pull/193) it was tricky to resize the images and round the corners in GIMP to match the existing images). So I quickly batch resized the original images that are saved [here](https://drive.google.com/drive/folders/1GfXK5v_csUZ0yksVNY4w3nnRLtjlhVUQ?usp=drive_link) (and that originally have regular corners) to try to match the size of the current ones on the site, and they look good on my local development server.

Looks like we'd only need to replace the current images with these new ones and @thekaveman's [PR #252](https://github.com/compilerla/compiler.la/pull/252) will close this issue without any other code changes since the classes `bg-white rounded` are already set on the images. Would it be ok for me to add a commit to my local branch with these new images and push to your [chore/team](https://github.com/compilerla/compiler.la/tree/chore/team) branch @thekaveman?
