### ISSUE TITLE
Design for the Work page

### ISSUE THREAD

**Issue by o-ram** [compilerla/compiler.la#61]
Draft and finalize design of the new `Work page`

**Comment by AnthonyRollins** [comment]
@segacy1 Here's the initial draft of some services and project content for the [work page](https://docs.google.com/document/d/1t3bATC0oa8nrnaUAz6O6nUHYOQbXQT_oqW22QSh1mbw/edit). Happy to go through this; @o-ram would love your eyes on this when you can. I still need to finish all the project descriptions, but I have a lot of content so far, and I need to reach out to others to complete the last few.

**Comment by o-ram** [comment]
@segacy1 a rough pass at the type of content we want for the [work page](https://docs.google.com/document/d/1t3bATC0oa8nrnaUAz6O6nUHYOQbXQT_oqW22QSh1mbw/edit) is complete. While not everything has a description associated with it yet, we do have a format in mind for how all copy should fit on this page, and I pasted that format in each section. Is this enough for you to run with for a first round of designs? LMK if it would be helpful for us to have a quick chat!

**Comment by segacy1** [comment]
This works for me to take a first design pass! I'll set up a call for us after the Compiler retreat to talk through initial mocks @o-ram @AnthonyRollins

**Comment by segacy1** [comment]
Hey @AnthonyRollins @o-ram, [here ](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=1751-1516&mode=design)are the updated designs with your feedback incorporated. We have two types of designs for the project section: floating text and cards. I’ve added some notes to explain each mock. If you have any questions, please add them here or tag me in a Figma comment!

I also wanted to highlight [a proposal](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=2873-11482&mode=design&t=PWa2qlEJRbIffQnt-4) for our service descriptions. In our last call, we discussed that it might make sense to talk about services on the work page differently than how we do on the capabilities statement so that it’s accessible (anyone who comes across our site can understand what we mean) and includes project management. It could use some fine-tuning, but here are the buckets I recommend. These would all need copy for their descriptions. 

FYI the copywriter's [copy doc](https://docs.google.com/document/d/1MVg0KN4Lkq3AiiTmotIC0dH_m-fRwItsLfJiok2N-B4/edit) I shared before Thanksgiving works for these mocks. Once the copywriter is done, I’ll plug in what they wrote and you can finetune the final copy. 

Please let me know which of these you like most + any additional edits you’d like to see. Once I get your feedback, I can quickly get mobile mocked and schedule time with dev to review in detail. Even though this isn’t _officially_ ready for dev review with copy and such, @machikoyasuda, @angela-tran,  @thekaveman you are all very welcome to leave notes for me too :)

**Comment by segacy1** [comment]
This work is done! I've included [a clean mock](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=3060-464&mode=design) for dev with no copy in it (aside from the projects with images), so that they can pull directly from that google doc for content. I'm adding the images for Data & Donuts and Benefits below. One thing for @AnthonyRollins and @o-ram to note: 

1. The images we have are a bit low-res at a bigger size, so I opted for our D&D logo. You're welcome to swap out if you'd prefer to try a pic of the team and speakers.
2. In the copy doc, you have Customer Success and D&D as the first two project. Since D&D is a project with a picture, it will be full width with it's own row. We'll need to swap the order so that it comes third. You can see what I mean in the Figma page I linked for dev.
<img width="1096" alt="benefits" src="https://github.com/compilerla/compiler.la/assets/33331853/a2f3eede-2aca-4854-8e12-d1b208495312">
<img width="1096" alt="D D" src="https://github.com/compilerla/compiler.la/assets/33331853/d5f1d981-1439-4995-bd37-81cc2c79646b">

cc: @angela-tran @machikoyasuda @thekaveman

**Comment by segacy1** [comment]
Also dropping in the graphic of the sign in the services section: 

[Work-Sign Graphic.zip](https://github.com/compilerla/compiler.la/files/14013302/Work-Sign.Graphic.zip)

**Comment by o-ram** [comment]
@srhhnry the final copy for the `work page` is ready to be inserted into the final designs that Segacy created. Could you please insert this copy in Figma so that it is prepared for us to give to dev? The copy is within [this google doc](https://docs.google.com/document/d/1MVg0KN4Lkq3AiiTmotIC0dH_m-fRwItsLfJiok2N-B4/edit) and the [designs are here](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=3060-464&mode=design), along with the graphic for the sign in the services section [Work-Sign Graphic.zip](https://github.com/compilerla/compiler.la/files/14013302/Work-Sign.Graphic.zip).

Please let @AnthonyRollins or I know if you have any questions! And thank you for doing this!

**Comment by srhhnry** [comment]
Screens are finalized with new copy. I also updated text styles and added alt tags in the Stark plugin. Let me know if I missed anything or there need to be any changes

https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt/compiler.la-design?type=design&node-id=3060%3A464&mode=design&t=BnDURqIpVpuu2lne-1

**Comment by o-ram** [comment]
Thank you @srhhnry! One request - can you update the copy to be sentence case instead of title case? [Per Machiko](https://www.figma.com/file/2gq3WJFdRFDefyHcgFMUGt?node-id=3139:324&mode=design#723244043), the rest of the website is in sentence case, and we want to match that. I can also update it within the Google doc first if you'd prefer - let me know what's easiest for you!

**Comment by srhhnry** [comment]
Much earlier today I had written that it's probably best to update the google doc first, then HOURS later I saw I had not pressed "Comment." That said, I've updated the mocks from comments, and let me know if there are any other changes :)

**Comment by o-ram** [comment]
No worries (I have done that myself too many times), thank you so much for making those changes! All looks good to me. And it's good to know that would've been the preference anyway because Anthony and I are thinking about copy process - once we get through the work page, we will likely want to discuss it with folks. So all helpful for me to hear!

**Comment by o-ram** [comment]
Since final designs and copy can all be found within the Figma file, I am closing this ticket and passing it along to Dev in #67
