### ISSUE TITLE
Development work for Footer

### ISSUE THREAD

**Issue by machikoyasuda** [compilerla/compiler.la#96]
Separating out Footer work from #65

<img width="1391" alt="image" src="https://github.com/compilerla/compiler.la/assets/3673236/37fc9cb7-64fd-4bea-a92a-4fadb88e0f46">

**Comment by angela-tran** [comment]
@machikoyasuda Should we move this to the "Home Page" milestone instead? I think that makes more sense since this was split off from #65 which is on the "Home Page" milestone.

I plan to merge in #87 either today or tomorrow, and if we move this ticket to "Home Page", we would be done with the "Careers & Job Page (phase 1)" milestone 😄
